scheduling/meetings/urls.py
from django.conf.urls import patterns, url
from meetings import views

urlpatterns = patterns('',
    url(r'^createMtn/$', views.create, name='create'),
    url(r'^create/$', views.create, name='create'),
    url(r'^createSuccess/$', views.createSuccess, name='createSuccess'),
    # url(r'^meeting_creation_success/$', views.meeting_creation_success, name='meeting_creation_success'),
	url(r'^organized/(?P<meeting_id>\w{6})/$', views.MtnOrganized, name="MtnOrganized"),
	url(r'^organized/(?P<meeting_id>\w{6})/delete/$', views.delete, name="delete"),
	url(r'^organized/(?P<meeting_id>\w{6})/update/$', views.updateMtn, name="updateMtn"),
	url(r'^organized/(?P<meeting_id>\w{6})/update/update/$', views.update, name="update"),
	url(r'^organized/(?P<meeting_id>\w{6})/addInvitees/$', views.addInvitees, name="addInvitees"),
	url(r'^invited/(?P<meeting_id>\w{6})/respond/$', views.respond, name="respond"),
	url(r'^invited/(?P<meeting_id>\w{6})/responded/$', views.responded, name="responded"),
	url(r'^invited/(?P<meeting_id>\w{6})/responded/respond/$', views.respond, name="respond"),
	url(r'^invited/(?P<meeting_id>\w{6})(?:/(?P<validity>\w{7,11}))?/$', views.MtnInvited, name="MtnInvited"),
	url(r'^ajaxTest/$', views.ajaxTest, name="ajaxTest"),
	)

scheduling/scheduling/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^', include('userprofile.urls')),
	(r'^jasmineTest/$', include('django_jasmine.urls')),
	(r'^loggedin/', include('meetings.urls', namespace='meetings')),
	# DO I NEED TO CHANGE THIS???
	url(r'^database/admin/', include(admin.site.urls)),
	url(r'^$',  'scheduling.views.index'),
	url(r'^ready/$',  'scheduling.views.ready'),
	url(r'^auth/$',  'scheduling.views.auth_view'),
	url(r'^logout/$', 'scheduling.views.logout'),
	url(r'^loggedin/$', 'scheduling.views.loggedin', name='loggedin'),
	url(r'^invalid/$', 'scheduling.views.invalid_login'),
	# registration   
	url(r'^register/$', 'scheduling.views.register_user'),
	url(r'^register_success/$', 'scheduling.views.register_success'),
)

scheduling/meetings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime


class Meeting (models.Model):
	name = models.CharField(max_length = 20)
	location = models.CharField(max_length = 20)
	description = models.CharField(max_length = 100)
	proposed = models.CharField(max_length = 200)
	organizer = models.ForeignKey(User, related_name='meetings_organized')
	invited = models.ManyToManyField(User, related_name='meetings_invited')
	meeting_id = models.CharField(max_length = 7)
	result = models.CharField(max_length = 20)
	invitedList = models.CharField(max_length = 1000)
	pub_date = models.DateTimeField('date published')
	visibility = models.BooleanField(default = False)
	def __str__(self):
		return self.name

class Respond(models.Model):
	choice = models.CharField(max_length=50 , blank = True)
	preference = models.CharField(max_length=50, blank = True)
	pub_date = models.DateTimeField('date published')
	responder = models.ForeignKey(User, related_name='response')
	responder_unregistered = models.CharField(max_length=10, )
	meeting = models.ForeignKey(Meeting,related_name='responses')
	def __str__(self):
		return self.choice

scheduling/meetings/forms.py
# -*- coding: utf-8 -*- 
from django import forms
import re
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import EMPTY_VALUES
from django.forms.fields import Field
my_default_errors = {
    'required': '这个格子是必填的',
    'invalid': 'Enter a valid value',
}

def unzipEmails(value):
    if value in EMPTY_VALUES:
        return []
    value = value.replace(',', ';')
    value = [item.strip() for item in value.split(';') if item.strip()]

    return list(set(value))

class CommaSeparatedEmailField(Field):
    description = _(u"E-mail address(es)")

    def __init__(self, *args, **kwargs):
        self.token = kwargs.pop("token", ";")
        super(CommaSeparatedEmailField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if value in EMPTY_VALUES:
            return []
        value = value.replace(',', ';')
        value = [item.strip() for item in value.split(self.token) if item.strip()]

        return list(set(value))

    def clean(self, value):
        """
        Check that the field contains one or more 'comma-separated' emails
        and normalizes the data to a list of the email strings.
        """
        value = self.to_python(value)

        if value in EMPTY_VALUES and self.required:
            raise forms.ValidationError(_(u"会议总得有个名称吧"))

        for email in value:
            if not re.match('[a-zA-Z0-9-]{1,}@([a-zA-Z0-9\.])?[a-zA-Z0-9]{1,}\.[a-zA-Z0-9]{1,4}', str(email)):
                raise forms.ValidationError(_(u"'%s' 不是一个有效的邮箱地址，请重新输入！") % email)
        return value

class MtnCreationForm(forms.Form):
    name = forms.CharField(label="会议名称", required = True, max_length = 20, error_messages = my_default_errors,)
    location = forms.CharField(label="会议地点", required = False, max_length = 20, error_messages = my_default_errors,)    
    description = forms.CharField(label="会议描述", required = False, max_length = 100, )
    share = CommaSeparatedEmailField(label="邀请", error_messages = my_default_errors,)

scheduling/meetings/views.py
# -*- coding: utf-8 -*- 
import re
import string
import random
from time import mktime, strptime
from datetime import datetime, date, timedelta
from django.core.context_processors import csrf
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.core.validators import EMPTY_VALUES
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils import timezone
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from meetings.models import Meeting, Respond
from forms import MtnCreationForm
from scheduling.forms import MyRegistrationForm
import json
# Define the date row

def unzipEmails(value):
    if value in EMPTY_VALUES:
        return []
    value = value.replace('$', ',')
    value = value.replace(',', ';')
    value = [item.strip() for item in value.split(';') if item.strip()]

    return list(value)
def unzipEmailsForInvitePage(value):
    result = unzipEmails(value)
    number = len(result)
    result[0] = result[0].replace(str(number), '', 1)

    return result

def invitedEmailList(value):
    value = '$'.join(unzipEmails(value))    
    return value
def inviteesAdditionParser(value):
    value = '$'.join(unzipEmails(value))
    value = '$' + value

    return value 
def giveDate(num):
    if num == 0: return '周日'
    if num == 1: return '周一'
    if num == 2: return '周二'
    if num == 3: return '周三'
    if num == 4: return '周四'
    if num == 5: return '周五'
    if num == 6: return '周六'
today_date = date.today().weekday()
global datesForData #Define the data processing needs
datesForData = [date.today(), \
                date.today()+timedelta(days = 1),\
                date.today()+timedelta(days = 2),\
                date.today()+timedelta(days = 3),\
                date.today()+timedelta(days = 4),\
                date.today()+timedelta(days = 5),\
                date.today()+timedelta(days = 6)]
global display
display = [giveDate(today_date),\
    giveDate((today_date+1)%7),\
    giveDate((today_date+2)%7),\
    giveDate((today_date+3)%7),\
    giveDate((today_date+4)%7),\
    giveDate((today_date+5)%7),\
    giveDate((today_date+6)%7)]
#Define the clock col
clock = []
for num in range(0,11):
    k = (num*2 + 5);
    if k > 12:
        clock.append(str(k%12)+"pm");
    elif k < 12 :
        clock.append(str(k%12)+"am");
#conversation for organizer page
def dateIntodateConversaion(value):
    now = datetime(2014, int(value[:2]), int(value[-2:])).weekday()
    now = giveDate(now + 1) 
    if now == None:
        now = '周日'
    return now.decode('utf-8')
#data processing    
def singleProcessor(string):
    if string[0] == '0':
        if string[2] == '3':
            k = 1
        else: 
            k = 0
        k = k + 2*(int(string[1]) - 5)
    else:
        if string[2] == '3':
            k = 1
        else: 
            k = 0
        k = k + 2*(int(string[0:2]) - 5)

    return k

def dateProcessor(timestring):
    #conver string to datetime object
    a = strptime(timestring, "%m%d%Y")
    a = datetime.fromtimestamp(mktime(a))
    a = a - datetime.today()
    a = a.days
    return a + 2

def processor(proposed): #takeproposed raw data, return the dates in format
    tempStorage = []
    num = len(proposed)/16
    for i in range(0,num):
        p = singleProcessor(proposed[16*i:16*(i+1)-12])
        n = singleProcessor(proposed[16*(i+1)-12:16*(i+1)-8])
        w = dateProcessor(proposed[16*i+8:16*i+16]) 
        tempStorage.append(p)
        tempStorage.append(n)
        tempStorage.append(w)
    
    return tempStorage

def descriptionProcessor(proposed): 
    tempStorage = []
    num = len(proposed)/16
    for i in range(0,num):
        tempStorage.append(proposed[0+i*16:2+i*16]+":"+proposed[2+i*16:4+i*16])
        tempStorage.append('-')
        tempStorage.append(proposed[4+i*16:6+i*16]+":"+proposed[6+i*16:8+i*16])
    return tempStorage
#organizer page's display info processor
def organizerPageProcessor(proposed):
    tempStorage = []
    num = len(proposed)/16
    for i in range(0,num):
        date = proposed[16*i+8:16*i+10]+'/'+proposed[16*i+10:16*i+12]
        weekday = dateIntodateConversaion(date)
        tempStorage.append(date+""+weekday)
        tempStorage.append(proposed[0+i*16:2+i*16]+":"+proposed[2+i*16:4+i*16]+'-'+proposed[4+i*16:6+i*16]+":"+proposed[6+i*16:8+i*16])
    tempStorage = [x+y for x,y in zip(tempStorage[0::2], tempStorage[1::2])]
    #arrange according to date/time
    tempStorage.sort()
    return tempStorage
#6-digit random id generator
def index_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

a ={}
a['clock'] = clock
a['date'] = display
a['datesForData'] = datesForData

#def createMtn (request):
#    a = {}
#    a.update(csrf(request))
#    a['user'] = request.user
#    a['clock'] = clock
#    a['date'] = display
#    a['datesForData'] = datesForData
#    a['list_organized'] = request.user.meetings_organized.all()
#    a['list_invited'] = request.user.meetings_invited.all()
#    return render_to_response("meetings/createMtn.html", a)

#EMAIL************************************************************************

from django.template.loader import get_template
from django.template import Context
from django.core.mail import EmailMultiAlternatives
def sendInvitation(sender, invitee, meeting_id, meeting_name):
    htmly = get_template('meetings/inviteEmail.html')
    d = Context({'sender':sender.username,'id': meeting_id, 'name': meeting_name })
    subject, from_email, to = u'您收到了一个来自%s的速议邀请' % sender.username, sender.email, invitee
    text_content = 'http://www.suyi1.com/loggedin/invited/%s/' % meeting_id
    html_content = htmly.render(d)
    msg = EmailMultiAlternatives(subject, text_content, from_email, to)
    msg.attach_alternative(html_content, "text/html")
    msg.send(fail_silently=True, )

def create(request):
    # the raw value for result
    if request.method == "POST":
        form = MtnCreationForm(request.POST)
        if form.is_valid():
            length = len(request.POST.get('proposed'))/16
            inviteData = request.POST.get("share")
            new_meeting_object = Meeting(invitedList = invitedEmailList(inviteData), result = ''.join(map(str, [k for k in range(0,length)])), meeting_id = index_generator(), description=request.POST.get('description') ,location= request.POST.get('location'), proposed = request.POST.get('proposed'), name=request.POST.get('name'), pub_date=timezone.now(), organizer=request.user)
            new_meeting_object.save()
            if not request.POST.get('visibility') == 'True':
                new_meeting_object.visibility = True;
                new_meeting_object.save()
            share = unzipEmails(inviteData) # get the multiple emails
            for address in share:
                try: 
                    u = User.objects.get(email = address)
                    new_meeting_object.invited.add(u)
                except ObjectDoesNotExist:
                    try:
                        u = User.objects.get(username = address)
                        new_meeting_object.invited.add(u)
                    except ObjectDoesNotExist:
                        pass
                new_meeting_object.save()
            sendInvitation(request.user, share, new_meeting_object.meeting_id, new_meeting_object.name)
            request.session['meeting_name'] = new_meeting_object.name
            request.session['meeting_id'] = new_meeting_object.meeting_id

            return HttpResponseRedirect('/loggedin/createSuccess/')
    else:
        form = MtnCreationForm()
    a = {}
    a.update(csrf(request))
    a['form'] = form
    a['user'] = request.user
    a['clock'] = clock
    a['date'] = display
    a['datesForData'] = datesForData
    a['list_organized'] = request.user.meetings_organized.all()
    a['list_invited'] = request.user.meetings_invited.all()
    return render_to_response("meetings/createMtn.html", a)

def createSuccess(request):
    b = a
    b['user'] = request.user
    b['list_organized'] = request.user.meetings_organized.all()
    b['list_invited'] = request.user.meetings_invited.all()  
    b['name'] = request.session['meeting_name']
    b['id'] = request.session['meeting_id']
    return render_to_response('meetings/meeting_creation_success.html', b)

def MtnOrganized(request, meeting_id):
    meeting = Meeting.objects.get(meeting_id = meeting_id)
    b = {}
    b.update(csrf(request))
    b['clock'] = clock
    b['date'] = display
    b['datesForData'] = datesForData
    b['meeting'] = meeting
    b['user'] = request.user
    b['list_organized'] = request.user.meetings_organized.all()
    b['list_invited'] = request.user.meetings_invited.all()     
    b['data'] = processor(meeting.proposed)  
    b['length'] = len(b['data'])/3
    length = len(b['data'])/3
    b['specificTimeDispaly'] = descriptionProcessor(meeting.proposed)
    b['infoOnTop'] = organizerPageProcessor(meeting.proposed)
    b['amountOfAvail'] = [x for x in range(0, b['length'])]
    b['listOfEmail'] = ""
    for name in unzipEmails(meeting.invitedList):
    	b['listOfEmail'] = b['listOfEmail'] + "<li>" + name + "</li>"
    responsesCount = str(meeting.responses.count())
    if responsesCount in EMPTY_VALUES:
    	responsesCount = '0'
    b['replyCondition'] =  responsesCount + "/" + str(meeting.invitedList.count("$")+1) + u" 位被邀请者已答复"
#processing for responses--------------
    k = '<td class="">&#32</td>'
#first row
    responders = meeting.responses.all()
    w = [e.responder.username for e in responders]
    invitees = meeting.invited.all()
    for invitee in w:
    	k = k + '<td class ="Answered " >'+invitee+'</td>'
    for invitee in invitees:
    	if invitee.username not in w:
    		k = k + '<td class ="unAnswered ">'+invitee.username+'</td>'
    k = '<tr>'+k+'</tr>'	
#other rows
    counter = -1 

scheduling/meetings/templates/meetings/createMtn.html
{%extends "loggedin.html"%}
{% load static %}
{% load crispy_forms_tags %}

<body>

{% block content%}
<div class="row" style="margin-top: -5px">
  <div class="col-md-10">
<div id="progressBar" style="width:116%;" class="progress">
  <div  id="progressAnimation" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: 1%">  </div>
  </div>
</div>
</div>
  <div id="createPageFirst">
<div class="row" style="margin-top: 8%;">
  <div class="col-md-offset-2 col-md-6">
{% for field in form %}
  {{field.error}}
{% endfor %}

<form id="createForm" class="outline" action="/loggedin/create/" method="POST">


<div id="div_id_name_jia" class="form-group"><label for="id_name" class="control-label  requiredField">
        会议名称<span class="asteriskField">*</span></label><div class="controls "><input class="textinput textInput form-control" id="name" maxlength="20" name="name" type="text"> </div></div><div id="div_id_location_jia" class="form-group"><label for="id_location" class="control-label ">
        会议地点
      </label><div class="controls "><input class="textinput textInput form-control" id="location" maxlength="20" name="location" type="text"> </div></div><div id="div_id_description_jia" class="form-group"><label for="id_description" class="control-label ">
        会议描述
      </label><div class="controls "><input class="textinput textInput form-control" id="description" maxlength="100" name="description" type="text"> </div></div>

<div class="form-group">
<div class="row">
  <div class="col-md-10">
    <h5>其他选项</h5>
  </div>

</div>
<input class="" type="checkbox" id="id_visibility" value="True" name="visibility">
<label for="visibility">我不想要被邀请者看到其他被邀请者</label>
</div>
</form>
  <div class="col-md-offset-8">
    <button style="margin-top: -50px;" class="btn btn-info pull-right" id="nextStep">下一步：选择时间</button>
  </div>
  </div>
</div>
</div>

<div id="createPageSecond">
<div class="row">
  <div class="col-md-4">
    <button id="lastStep" class="btn btn-default">上一步：会议信息</button>  
  </div>
  <h4 class="col-md-5 col-md-offset-1">
      请选择会议时间选项
  </h4>
  <div >
    <button id="nextStep2" class="btn btn-info">下一步：会议邀请</button>
  </div>
</div>
<div class="row">
  <div class="col-md-12" style="margin-top: 5%;">
<div id="scheduleUIwrapper">
<div id='scrollWindow'>
  <div id="CalWrapper">
 <div id="clockWrapper">
  {% for time in clock %}
  <h5 id ="clockTime">{{ time }}</h5><br/> 
  {% endfor %}
  </div><!--end of clockWrapper-->
  <div id="container">
  <div id="lines_container"></div>
  <div id="col_1" class="calCol"></div>
  <div id="col_2" class="calCol"></div>
  <div id="col_3" class="calCol"></div>
  <div id="col_4" class="calCol"></div>
  <div id="col_5" class="calCol"></div>
  <div id="col_6" class="calCol"></div>
  <div id="col_7" class="calCol"></div>
  </div>
  </div><!--end of CalWrapper-->
</div>
<div id="dateWrapper">
<a href='#' class="scopeSwitch" id='scopeLeft'>上周</a>
{% for day in date %}
<h5 class="dateSpacer text-center" id="dateSpacer_{{forloop.counter}}">{{ day }}</h5>
{% endfor %}<!--header-->
{% for day in datesForData %}
<h5 class="datesForData text-center" id="datesForData_{{forloop.counter}}">{{ day|date:"SHORT_DATE_FORMAT" }}</h5>
{% endfor %}<!--header-->
<a href="#" class="scopeSwitch" id="scopeRight">下周</a>
</div><!--end of dateWrapper-->
</div><!--end of scheduleUIWrapper-->
</div>
</div>
</div>

<div id="createPageThird" style="display:none;">
  <div class="row">
  <div class="col-md-4">
    <button id="lastStep2" class="btn btn-default">上一步：选择时间</button>  
  </div>
</div>
<div class="row">
  <div class="col-md-offset-2 col-md-6 outline" style="margin-top: 5%;">
<div class="row">
  <div class="container">
    <h3 id="meetingTitle"></h3>
    <h4 id="meetingDescription"></h4>
  </div>
</div>
<form action="/loggedin/create/" method="POST" style="margin-top: 30px;">{% csrf_token %}
  <div class="row">
    <div class="col-md-10">
{{ form|crispy }}
</div>
</div>
<p>请输入你想邀请的人的邮箱，用逗号隔开</p>
<input class="" id="visibility"style="display:none;" type='checkbox' value='True' name='visibility'/>

<input type="hidden" id="dataStorage"name= "proposed">
<button id="submit" onclick="return validateMultipleEmailsCommaSeparated();"class="btn btn-success pull-right" type="submit" name="submit">&nbsp;创建会议&nbsp;</button>
</form>
    </div>
  </div>
</div>
<!--JQEURY************************************************************************
**********************************************************************************-->
  <script type="text/javascript" src="{% static 'meetings/js/UI.js' %}"> // visualize the Y grid</script>

{%endblock%}
</body>

scheduling/meetings/templates/meetings/meeting_creation_success.html
{%extends "loggedin.html" %}

{%block content%}

<div class="row" style="margin-top: -5px">
  <div class="col-md-10">
<div id="progressBar" style="width:116%;" class="progress">
  <div  id="progressAnimation" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100" style="width: 66%">  </div>
  </div>
</div>
</div>
<div class="row" style=" margin-top:5%;">
<div class="col-md-offset-1 col-md-9 outline">
<div class="row">
	<div class="col-md-1" style="margin-top:2%;">
		<div class="glyphicon glyphicon-check symbol" ></div>
	</div>
	<div class="col-md-11">
		<h1><strong>{{name}}</strong>的邀请函已经发出，请耐心等待回复！</h1>
	</div>
</div>
<div class="row" >
	<div class="">

	</div>
</div>
<div class="row" style="margin-top:5%;">
	<div class="">
		<a href="{% url 'loggedin' %}">返回主页</a>
	</div>
</div>
<div class="row" style="margin-top:5%;">
	<div class="">
		<h4>如果你的朋友不幸丢失了链接，请将下面的链接发给他们:</h4>

		<input id="inviteLink" style="margin-top: 3%;"class="form-control" value="http://www.suyi1.com/loggedin/invited/{{ id }}/"/>

	</div>
</div>

</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
		$("#progressAnimation").css("width", "100%");

});
</script>
<script type="text/javascript">
window.onload = function(){
  var text_input = document.getElementById ('inviteLink');
  text_input.focus();
  text_input.select();
}
</script>
		{%endblock%}

scheduling/meetings/templates/meetings/meeting_organized.html
{%extends "loggedin.html"%}

{% block content%}
      {% csrf_token %}

<div class="row pageTop">
  <div class="col-md-offset-2 col-md-8">
<div id = "wrapper" class="outline" style="padding-left: 50px;">
<div class="row">
  <h1 class="col-md-10">{{meeting.name}}</h1>
  <div class="col-md-2">
  <div class="row" style="margin-top:23px;">
   <form method="POST" action="update/">{% csrf_token %}<button class="btn btn-default" href='update/'>编辑</button></form><form method="POST" action="delete/">{% csrf_token %}   <button class="btn btn-warning" onclick ="return confirm('您真的要删除这个会议吗?')" value='' type='submit'>删除</button></form>
</div></div>
</div>
<div class="row">
  <div class="row rowMargin"><p><strong>创建时间</strong>：{{meeting.pub_date}}</p></div>
  <div class="row rowMargin"><p><strong>会议描述</strong>：{{meeting.description}}</p></div>
  

  <div class="row rowMargin">
      

      <input id="ajaxTest" type="text"/>
      <ul id="ajaxTestResult"></ul>

  </div>


  <div class="row rowMargin"><p><strong>会议地点</strong>：{{meeting.location}}</p></div>
  <div class="row rowMargin"><h5><strong>回复情况</strong>：{{replyCondition}}&nbsp; <a href="#" onclick = "viewFullList()" > 查看完整邀请者名单 </a></h5></div>{%csrf_token%}
  <br>
  <ul style = "display:none; " id = "viewFullList">
  {{ listOfEmail|safe }}
  <li><form onsubmit="return validateForm();" method='POST' action='addInvitees/' >{% csrf_token %}
    <input style="margin-top: 10px;" id='addInvitees' name='addInvitees' placeholder="请用逗号分开"/>
    <button id="addInviteesButton" style="padding: 0;margin-left: 10px;border: none;background: none;" type='submit' >+</button><div id="addInviteesError"></div></form></li>
  </ul>
  <div class="table-responsive">

    {{ table|safe }}

  </div>
  <br>
<div class="row" style="margin-top:5%;">
  <div class="col-md-9">
    <h4>如果你的朋友不幸丢失了链接，请将下面的链接发给他们:</h4>

    <input id="inviteLink" style="margin-top: 3%;"class="form-control" value="http://www.suyi1.com/loggedin/invited/{{ meeting.meeting_id }}/"/>

  </div>
</div>
<!-- data processing -->
  {% for num in data %}
 	<div style="display:none;"id="data_{{forloop.counter}}">{{num}}</div>
  {%endfor%}
  {%for num in specificTimeDispaly%}
 	<div style="display:none;"id="specific_{{forloop.counter}}">{{num}}</div>
  {%endfor%}
  <div style="display:none;"id="lengthStorage">{{length}}</div>
  <div style="display:none;"id="resultStorage">{{meeting.result}}</div>

</div><!--end of wrapper-->
</div>
</div>
</div>
<!--JQEURY************************************************************************
**********************************************************************************-->
  <script type="text/javascript">
window.onload = function(){
  var text_input = document.getElementById ('inviteLink');
  text_input.focus();
  text_input.select();
}
</script>
  <script type="text/javascript"> // visualize the Y grid
//***********************************window-size********************************
  var GLOBAL = {};
  GLOBAL.userHeight=$(window).height();
  var viewFullList = function(){
    if($("#viewFullList").css("display") == "none"){
    $("#viewFullList").fadeIn("fast");
    }
    else{
    $("#viewFullList").fadeOut("fast"); 
    }
  }
var email = "[A-Za-z0-9\._%-]+@[A-Za-z0-9\.-]+\.[A-Za-z]{2,4}";
var re = new RegExp('^'+email+'(;\\n*'+email+')*;?$');

function validateForm()
{
var x = $("#addInvitees").val();
if (x == null || x == "")
  {
  $("#addInviteesError").html('<p style="color: #a94442;" class="help-block"><strong>邀请人不能为空</strong></p>');
  return false;
  }
else if(!re.test(x)){
  $("#addInviteesError").html('<p style="color: #a94442;" class="help-block"><strong>您输入的地址有误</strong></p>');
  return false;
}
}


//&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&7core&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
</script>
{%endblock%}